### ISSUE TITLE
Animal size filter

### ISSUE THREAD

**Issue by WynandBothma** [Galoot/whispers_of_the_wild#4]
Animal size filter - Slider

**Comment by WynandBothma** [comment]
http://egorkhmelev.github.io/jslider/ - Lyk nogals naby aan wat ons wil he.
http://www.jqueryrain.com/?eL8Uj3ZQ
http://www.jqueryrain.com/demo/jquery-range-slider/

**Comment by rudiminty** [comment]
@WynandBothma, slider is now functional, just needs to be styled.

**Comment by WynandBothma** [comment]
Hey Rudi, awesome! Sal kyk baie dankie!

Kind Regards,

sig_logo2.jpg

Wynand Bothma | Founder / Operator

Web & Mobile Solutions • Design • Print • Hosting

C: 082 775 6561     T : 087 151 1610    E: wynand@galoot.co.za

W:  http://www.galoot.co.za www.galoot.co.za      F:  https://www.facebook.com/pages/Galoot-Design/121682774513133?fref=ts facebook.com/Galoot-Design
