### ISSUE TITLE
Profile Nav & Media player footer bar – Show / Hide Functionality

### ISSUE THREAD

**Issue by WynandBothma** [Galoot/whispers_of_the_wild#7]

**Comment by WynandBothma** [comment]
@rudiminty

**Comment by rudiminty** [comment]
@WynandBothma , some initial tests done to enable a show/hide of the profile options and footer.

**Comment by rudiminty** [comment]
@WynandBothma , this is done and I've committed it, just needs styling now I think.
please test on the apple devices.

**Comment by rudiminty** [comment]
@WynandBothma , the show / hide is completed now, but I see the styling on the footer in portrait mode needs some work still, as if all of the contents of the footer is more than the 50px height specified.
